### ISSUE TITLE
[CHORE] Add rate limiting for API usage

### ISSUE THREAD

**Issue by aminah-io** [gitcoinco/passport-scorer#28]

**Comment by nutrina** [comment]
This seems like a good starting point: https://django-ratelimit.readthedocs.io/en/stable/index.html

**Comment by nutrina** [comment]
What is the exact desired outcome? Here is a potential solution (the easiest):

**Solution A**
1. we can limit each of the community APIs ( https://api.scorer.gitcoin.co/docs ) to a given rate (100/m for example)
2. this limit applies for each API individually
3. the key for which the requests get counted for is the API key

This means, the user can call each community API 100 / m with each API key (if he has 2 API key, he can make 100 calls with the 1st one, and 100 with the 2nd one).

Other more complex (but probably better) rate limiting solutions:

**Solution B**
1. count the number of requests against the account (instead of the API key) - this means regardless if how many PAI keys a user has, he can only make 100 calls / m
2. use a global count for the APIs (do not count API calls individually). This means the user gets 100 calls / min regardless which API path he calls (they all get counted towards the same variable).


Questions:
1. how shall we configure the rate limit?
    a. shall the rate limit be configured globally in our backend? 
    b. Or shall we allow setting that in our admin in the accounts?

    --> I think b make more sense

**Comment by Kweiss** [comment]
- Tier 1: 125 req / 15 min as the lowest API tier.
- Tier 2: 350 req / 15 min as the lowest API tier.
- Tier 3 (Allo): 2000 req / 15 min

**Comment by Kweiss** [comment]
This will be implemented based on the API Key level. Key access can be managed on the backend to start. Eventually users can select the different API access levels.

**Comment by Kweiss** [comment]
Also need to add:

- [ ] tier selection to Admin (tiers 1-3) when editing API key settings
- [ ] Add account address to search in API key settings (accountapikey) screen. We want to make it easy to find API keys when folks are searching
- [ ]
